# Generated by Django 5.2.6 on 2025-09-30 13:17

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("sku_id", models.CharField(blank=True, max_length=128, null=True)),
                ("name", models.TextField()),
                ("manufacturer_name", models.TextField(blank=True, null=True)),
                ("marketer_name", models.TextField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("pack_size_label", models.TextField(blank=True, null=True)),
                ("short_composition", models.TextField(blank=True, null=True)),
                ("is_discontinued", models.BooleanField(default=False)),
                ("available", models.BooleanField(default=True)),
                (
                    "name_tsv",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, editable=False, null=True
                    ),
                ),
            ],
            options={
                "db_table": "search_medicine",
            },
        ),
    ]
